CREATE TABLE thermostatTrackingdb.trackingData (
  tracking_id INT(11) NOT NULL AUTO_INCREMENT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fanOn TINYINT(1) NOT NULL,
  heatOn TINYINT(1) NOT NULL,
  auxOn TINYINT(1) NOT NULL,
  acOn TINYINT(1) NOT NULL,
  temp DOUBLE NOT NULL,
  rawData VARCHAR(255) NOT NULL,
  PRIMARY KEY (tracking_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3923
AVG_ROW_LENGTH = 127
CHARACTER SET utf8
COLLATE utf8_general_ci;